---
- hosts: all
  become: true
  vars:
    - url: https://www.free-css.com/assets/files/free-css-templates/download/page261/yeinydd.zip
      image: httpd:2.2
      name: webserver
      website_name: yeinydd

  tasks:
    - name: Install aptitude
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install system packages
      apt: 
        name={{ item }} 
        state=latest 
        update_cache=yes
      with_items:  
        - apt-transport-https
        - software-properties-common
        - python3-pip
        - python3-setuptools
        - unzip 
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker  

    - name: Download website
      get_url:
        url: "{{ url }}"
        dest: /tmp/website.zip

    - name: Upload httpdconf file
      template:
        src: httpd.conf
        dest: /root/

    - name: Extract website files
      unarchive:
        src: /tmp/website.zip
        dest: /tmp/
        remote_src: true

    - name: Copy website files to root
      copy:
        src: /tmp/{{ website_name }}
        dest: /root/
        remote_src: true

    - name: Pull an image
      docker_image:
        name: "{{ image }}"
        source: pull

    - name: "Copy httpd.conf to root"
      copy:
        src: httpd.conf
        dest: /root/

    - name: Launch apache webserver container
      docker_container:
        name: "{{ name }}"
        image: "{{ image }}"
        state: started
        ports:
        - "80:8080"
        volumes:
        - /root/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - /root/{{ website_name }}:/usr/local/apache2/htdocs/

